export const Types = {
    TOTAL_USERS: 'TOTAL_USERS',
    TOTAL_QUIZS: 'TOTAL_QUIZS',
    TOTAL_EXAMS: 'TOTAL_EXAMS',
    TOTAL_CLASSES: 'TOTAL_CLASSES',
    
    LOADING_USERS: 'LOADING_USERS',
    LOADING_QUIZS: 'LOADING_QUIZS',
    LOADING_EXAMS: 'LOADING_EXAMS',
    LOADING_CLASSES: 'LOADING_CLASSES',
};