export const Types = {
    LIST_USER_CLASSES: 'LIST_USER_CLASSES',
    DETAIL_CLASS_BY_CODE: 'DETAIL_CLASS_BY_CODE',
    USER_JOIN_CLASS_REQUEST: 'USER_JOIN_CLASS_REQUEST',
    CLEAR_CLASS_BY_CODE: 'CLEAR_CLASS_BY_CODE',
};