export const Types = {
    LIST_USER_EXAM_EVENTS: 'LIST_USER_EXAM_EVENTS',
    DETAIL_EXAM_EVENT_BY_CODE: 'DETAIL_EXAM_EVENT_BY_CODE',
    USER_JOIN_EXAM_EVENT_REQUEST: 'USER_JOIN_EXAM_EVENT_REQUEST',
    CLEAR_EXAM_EVENT_BY_CODE: 'CLEAR_EXAM_EVENT_BY_CODE',
};